#############################################################################
# Given a MAF file, its index generated by `mafutils index`, and a bed file,
# this script will output the alignment blocks from the MAF file that overlap
# the regions specified in the bed file. The output will be trimmed to only
# include the exact portion of the alignment block that overlaps the bed region.
#
# Gregg Thomas, April 2025
#############################################################################

"""
mafutils fetch

This script fetches alignment blocks from a MAF (Multiple Alignment Format) file
that overlap regions specified in a BED file. It works in two modes:

    Block mode:
        - Uses a block-level index
        - Extracts blocks overlapping each [start, end) BED interval
        - Trims blocks to exactly match the specified region
        - Output files are named by region ID or scaffold.counter (e.g., chr1.1.maf)

    Scaffold mode:  
        - Uses a scaffold-level index
        - Treats the BED file as a list of scaffold names (only column 1 is required)
        - Extracts all alignment blocks for each scaffold from the MAF
        - Output files are named by scaffold (e.g., chr1.maf, chrZ.maf)

Parallelization:
    - Block mode is parallelized by region
    - Scaffold mode is parallelized by scaffold
    - The number of processes can be controlled with --processes

Required input:
    - A MAF file (.maf, .maf.gz, or bgzip-compressed .maf)
    - A MAF index file (from `mafutils index`; defaults to <MAF_FILE>.block.idx
      or <MAF_FILE>.scaffold.idx if not given with --index)
    - A BED file

Optional arguments:
    --index, -i          Index file (default: derived from MAF_FILE)
    --outdir, -o         Output directory (default: current directory)
    --processes, -p      Number of parallel processes (default: 1)
    --mode, -m           Mode: 'block' or 'scaffold' (default: 'block')

Compression:
    - Uncompressed and bgzip-compressed MAFs get real random access, so
      --processes parallelizes normally.
    - Plain gzip-compressed MAFs cannot be randomly seeked efficiently (each
      seek can require re-decompressing everything before it), so fetch
      falls back to a single sequential pass regardless of --processes.

Usage:
    python -m mafutils fetch <maf_file> <bed_file> [--index FILE] [--outdir DIR] [--processes N] [--mode block|scaffold]

Examples:
    Block mode with 4 threads:
        python -m mafutils fetch alignment.maf regions.bed --processes 4

    Scaffold mode with default output:
        python -m mafutils fetch alignment.maf scaffolds.bed --mode scaffold
"""

import sys
import os
import re
import atexit
import logging
import bisect
import time
import traceback
from enum import Enum
from types import SimpleNamespace
from typing import Annotated, Optional
from concurrent.futures import FIRST_COMPLETED, ProcessPoolExecutor, wait
from collections import defaultdict, OrderedDict

import typer

from mafutils.lib import common as COMMON
from mafutils.lib import loginit as LOGINIT

#############################################################################

ADVISORY_NO_OVERLAP_REGIONS = 10000
ADVISORY_NO_OVERLAP_FRACTION = 0.10
WORKER_BLOCK_CACHE_MAX = 2048

WORKER_HEADER = None
WORKER_MAF_FILE = None
WORKER_MAF_COMPRESSION = None
WORKER_INDEX = None
WORKER_INDEX_FILE = None
WORKER_SCAFFOLD_RUNS = None
WORKER_OUTPUT = None
WORKER_SINGLE_OUTPUT = None
WORKER_SCAFFOLD_SUBDIRS = None
WORKER_AS_FASTA = None
WORKER_FASTA_HEADER = None
WORKER_EXPECTED_SPECIES = None
WORKER_FASTA_DEDUPE = None
WORKER_VERBOSE = None
WORKER_PROFILE = None
WORKER_MAF_FP = None
WORKER_BLOCK_CACHE = None

#############################################################################

class BasenameMode(str, Enum):
    id = "id"
    coords = "coords"
    count = "count"


class FastaHeaderMode(str, Enum):
    species_coords_id = "species-coords-id"
    species_coords = "species-coords"
    species_only = "species-only"


class FastaDedupeMode(str, Enum):
    none = "none"
    most_seq = "most-seq"


class FetchMode(str, Enum):
    block = "block"
    scaffold = "scaffold"

#############################################################################

def parseExpectedSpecies(args):
    expected = []
    seen = set()

    if args.expected_species:
        for sp in args.expected_species.split(","):
            sp = sp.strip()
            if sp and sp not in seen:
                expected.append(sp)
                seen.add(sp)

    if args.expected_species_file:
        with open(args.expected_species_file, "r", encoding="utf-8") as fp:
            for line in fp:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                if line not in seen:
                    expected.append(line)
                    seen.add(line)

    return expected

#############################################################################

def pick_chunk_size(num_regions, num_procs, min_size=100):
    n_batches = max(num_procs * 2, 1)
    batch_size = max(min_size, (num_regions + n_batches - 1) // n_batches)
    return batch_size

def chunker(seq, size=1000):
    for pos in range(0, len(seq), size):
        yield seq[pos:pos+size]

#############################################################################

def initBatchWorker(
    header,
    maf_file,
    maf_compression,
    index,
    output,
    single_output,
    as_fasta,
    fasta_header,
    expected_species,
    fasta_dedupe,
    verbose,
    profile,
    prefetched_cache=None,
    scaffold_subdirs=False,
    index_file=None,
    scaffold_runs=None,
):
    global WORKER_HEADER
    global WORKER_MAF_FILE
    global WORKER_MAF_COMPRESSION
    global WORKER_INDEX
    global WORKER_INDEX_FILE
    global WORKER_SCAFFOLD_RUNS
    global WORKER_OUTPUT
    global WORKER_SINGLE_OUTPUT
    global WORKER_SCAFFOLD_SUBDIRS
    global WORKER_AS_FASTA
    global WORKER_FASTA_HEADER
    global WORKER_EXPECTED_SPECIES
    global WORKER_FASTA_DEDUPE
    global WORKER_VERBOSE
    global WORKER_PROFILE
    global WORKER_MAF_FP
    global WORKER_BLOCK_CACHE

    WORKER_HEADER = header
    WORKER_MAF_FILE = maf_file
    WORKER_MAF_COMPRESSION = maf_compression
    WORKER_INDEX = index
    # Block mode streams the index from disk rather than receiving it: the
    # in-memory form is ~288 bytes/block (~67GB for a whole-genome index), and
    # passing it through initargs pickled that whole structure to EVERY worker.
    WORKER_INDEX_FILE = index_file
    WORKER_SCAFFOLD_RUNS = scaffold_runs
    WORKER_OUTPUT = output
    WORKER_SINGLE_OUTPUT = single_output
    WORKER_SCAFFOLD_SUBDIRS = scaffold_subdirs
    WORKER_AS_FASTA = as_fasta
    WORKER_FASTA_HEADER = fasta_header
    WORKER_EXPECTED_SPECIES = expected_species
    WORKER_FASTA_DEDUPE = fasta_dedupe
    WORKER_VERBOSE = verbose
    WORKER_PROFILE = profile

    # For gzip input, prefetched_cache already holds every block needed across
    # all regions, decoded in strictly-ascending file order (see
    # prefetchBlockCache) -- inserting it directly here (bypassing
    # getCachedBlockText's eviction check) means every later lookup is a
    # guaranteed hit, so no backward seeks ever happen during real processing.
    WORKER_BLOCK_CACHE = OrderedDict(prefetched_cache) if prefetched_cache else OrderedDict()

    WORKER_MAF_FP = COMMON.openMaf(maf_file, maf_compression, "rb")
    atexit.register(closeBatchWorker)

#############################################################################

def closeBatchWorker():
    global WORKER_MAF_FP
    if WORKER_MAF_FP is not None:
        WORKER_MAF_FP.close()
        WORKER_MAF_FP = None

#############################################################################

def parseIndex(index_file, LOG, mode="block"):
    """
    Parses either a block-level or region-level index file.

    For block mode:
        Returns: { scaffold: [ { ref_start, seq_length, offset_start, offset_end }, ... ] }

    For scaffold mode:
        Returns: { scaffold: (byte_start, byte_end) } — one entry per scaffold
    """
    index = {}

    with open(index_file, "r") as f:
        for line in f:
            if line.startswith("#") or not line.strip():
                continue
            fields = line.strip().split("\t")

            if mode == "block":
                if len(fields) < 7:
                    LOG.warning(f"Skipping malformed index line: {line.strip()}", file=sys.stderr)
                    continue
                scaffold = fields[0]
                try:
                    ref_start = int(fields[1])
                    ref_length = int(fields[2])
                    aln_length = int(fields[3])
                    offset_start = int(fields[6])
                    offset_end = int(fields[7])
                except ValueError:
                    continue
                entry = {
                    "ref_start": ref_start,
                    "ref_length": ref_length,
                    "aln_length": aln_length,
                    "offset_start": offset_start,
                    "offset_end": offset_end
                }
                index.setdefault(scaffold, []).append(entry)

            elif mode == "scaffold":
                if len(fields) != 3:
                    LOG.warning(f"Skipping malformed index line: {line.strip()}", file=sys.stderr)
                    continue
                scaffold = fields[0]
                try:
                    offset_start = int(fields[1])
                    offset_end = int(fields[2])
                except ValueError:
                    continue
                index[scaffold] = (offset_start, offset_end)

    # Sort block entries per scaffold
    if mode == "block":
        for scaffold in index:
            index[scaffold].sort(key=lambda x: x["ref_start"])
            index[scaffold] = {
                "entries": index[scaffold],
                "starts": [entry["ref_start"] for entry in index[scaffold]],
            }

    return index

#############################################################################

def readScaffoldRuns(scaffold_index_file):
    """
    Returns the scaffold index's rows in file order as
    [(scaffold, maf_start_byte, maf_end_byte), ...].

    Each row is a *run* of consecutive blocks for one scaffold, not a unique
    scaffold: a MAF may interleave scaffolds, so the same name can appear more
    than once. tests/example.maf does exactly this (chr4 ... chrX ... chr4),
    and assuming one run per scaffold silently loses the later blocks. The
    block index is in MAF order too, so these runs are also contiguous there.
    """
    runs = []
    with open(scaffold_index_file, "r", encoding="utf-8") as fp:
        for line in fp:
            if line.startswith("#") or not line.strip():
                continue
            fields = line.rstrip("\n").split("\t")
            if len(fields) < 3:
                continue
            try:
                runs.append((fields[0], int(fields[1]), int(fields[2])))
            except ValueError:
                continue
    return runs


def parseIndexLine(line):
    """
    Parses one block-index line into
    (scaffold, ref_start, ref_length, offset_start, offset_end), or None if the
    line is a comment/blank/malformed. Only the columns fetch actually needs.
    """
    if not line or line.startswith("#") or not line.strip():
        return None
    fields = line.rstrip("\n").split("\t")
    if len(fields) < 8:
        return None
    try:
        return (fields[0], int(fields[1]), int(fields[2]), int(fields[6]), int(fields[7]))
    except ValueError:
        return None


def _firstRecordAtOrAfter(fp, offset):
    """
    Seeks to `offset` and returns (record, record_offset) for the first
    COMPLETE record at or after it, or (None, None) at EOF.

    Index lines are variable-length, so there is no arithmetic from "record N"
    to a byte position -- but seeking to an arbitrary byte and discarding the
    partial line lands on a record boundary, which is what makes a binary
    search over the text file possible.
    """
    fp.seek(offset)
    if offset > 0:
        fp.readline()  # discard the (probably partial) line we landed inside
    while True:
        record_offset = fp.tell()
        line = fp.readline()
        if not line:
            return None, None
        record = parseIndexLine(line)
        if record is not None:
            return record, record_offset


def findIndexOffsetForMafByte(index_file, maf_offset, window=8192):
    """
    Byte offset into the block index of the first record whose block starts at
    or after `maf_offset` in the MAF.

    The search key is the block's MAF offset because that is the one column
    guaranteed to increase monotonically through the whole index -- scaffold
    name and ref_start are only sorted *within* a run, and a scaffold can have
    several runs (see readScaffoldRuns).

    Binary search by byte position: seek to a midpoint, skip the partial line,
    compare the first complete record, narrow. ~log2(filesize) probes, so ~35
    on a 35GB index regardless of how many records it holds. Returns an exact
    record boundary, since callers treat offsets as record starts.
    """
    size = os.path.getsize(index_file)
    with open(index_file, "r", encoding="utf-8") as fp:
        lo, hi = 0, size
        while hi - lo > window:
            mid = (lo + hi) // 2
            record, _ = _firstRecordAtOrAfter(fp, mid)
            if record is None:
                hi = mid
                continue
            if record[3] < maf_offset:
                lo = mid
            else:
                hi = mid
        _record, record_offset = _firstRecordAtOrAfter(fp, lo)
        return size if record_offset is None else record_offset


def computeRunIndexOffsets(index_file, runs):
    """
    Maps each scaffold-index run to where its records begin in the block index.

    One binary search per run (61 runs on the hamster data, 455 on the
    241-mammal file) done once at startup -- not per region. Run i's records
    occupy [offsets[i], offsets[i+1]).
    """
    return [findIndexOffsetForMafByte(index_file, maf_start) for _scaffold, maf_start, _maf_end in runs]


def iterIndexRecordsFrom(fp, offset):
    """
    Yields (record, record_offset) from `offset` forward on an already-open
    index handle. Streaming, so memory never scales with index size.

    `offset` MUST be an exact record boundary (both findIndexOffsetForMafByte
    and the record_offset values yielded here are). It deliberately does not
    skip a leading partial line -- doing so would drop the first record when
    resuming from a known boundary.
    """
    fp.seek(offset)
    while True:
        record_offset = fp.tell()
        line = fp.readline()
        if not line:
            return
        record = parseIndexLine(line)
        if record is not None:
            yield record, record_offset


#############################################################################

def parseBed(bed_file, LOG, mode="block"):
    """
    Parses the BED file into a list of region dictionaries.

    In "block" mode: expects at least 3 columns (scaffold, start, end)
    Each region has keys:
        - scaffold (chromosome)
        - start (integer, 0-based)
        - end (integer, non-inclusive)
        - basename (from column 4, if present; otherwise None)

    In "scaffold" mode: accepts 1+ columns; only uses first column (scaffold)
    """
    regions = []
    with open(bed_file, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            fields = line.split()
            if mode == "scaffold":
                scaffold = fields[0]
                region = {"scaffold": scaffold, "start": 0, "end": 0, "id": fields[3] if len(fields) >= 4 else None}
                regions.append(region)
            else:
                # block mode: require at least 3 columns (scaffold/start/end)
                try:
                    scaffold = fields[0]
                    start = int(fields[1])
                    end = int(fields[2])
                    region = {"scaffold": scaffold, "start": start, "end": end, "id": fields[3] if len(fields) >= 4 else None}
                    regions.append(region)
                except (IndexError, ValueError):
                    LOG.warning(f"Skipping malformed BED line: {line}", file=sys.stderr)
                    continue
    return regions

#############################################################################

def getMAFHeader(maf_file, maf_compression):
    """Return header lines (starting with ##) from the MAF file, skipping blank lines."""
    headers = []
    with COMMON.openMaf(maf_file, maf_compression, "rt") as fp:
        for line in fp:
            line = line.strip()
            if not line:  # Skip blank lines
                continue
            if line.startswith("##"):
                headers.append(line)
            else:
                break
    # print(f"Found {len(headers)} header lines in MAF file.")
    # print(f"Header lines:\n{headers}")
    # sys.exit();
    return "\n".join(headers) + "\n"

#############################################################################

def speciesFromSrc(src):
    return src.split(".", 1)[0] if "." in src else src

#############################################################################

WARNING_LABELS = {
    "missing-scaffold": "missing-scaffold",
    "multiple-strands": "multiple-strands",
    "no-overlap": "no-overlap",
    "trim-mismatch": "trim-mismatch",
}


def appendWarning(warning_state, code, message):
    if warning_state is None:
        return

    warning_state["count"] += 1
    warning_state["counts"][code] = warning_state["counts"].get(code, 0) + 1
    if warning_state["messages"] is not None:
        warning_state["messages"].append(message)


def formatWarningCounts(warning_counts):
    if not warning_counts:
        return "none"

    ordered_codes = [
        "no-overlap",
        "missing-scaffold",
        "trim-mismatch",
        "multiple-strands",
    ]
    summary_parts = []

    for code in ordered_codes:
        if code in warning_counts:
            summary_parts.append(f"{WARNING_LABELS[code]}={warning_counts[code]}")

    for code in sorted(warning_counts):
        if code not in WARNING_LABELS or code not in ordered_codes:
            summary_parts.append(f"{code}={warning_counts[code]}")

    return ", ".join(summary_parts)


def getFillString(fill_cache, fill_char, block_len):
    cache_key = (fill_char, block_len)
    if cache_key not in fill_cache:
        fill_cache[cache_key] = fill_char * block_len
    return fill_cache[cache_key]


def getCachedBlockText(maf_fp, entry):
    """
    Returns the decoded text of one block, via WORKER_BLOCK_CACHE.

    For compressed input (gz), the cache is pre-populated (see
    prefetchBlockCache) in strictly-ascending file order before any region
    is processed, so every lookup here is a guaranteed cache hit and the
    eviction path below is never reached for those entries -- this is what
    avoids backward seeks on gzip without needing per-worker parallel seeks.
    For uncompressed/bgzip input the cache just opportunistically saves a
    re-read/re-decode when multiple regions overlap the same block.
    """
    cache_key = (entry["offset_start"], entry["offset_end"])
    if cache_key in WORKER_BLOCK_CACHE:
        WORKER_BLOCK_CACHE.move_to_end(cache_key)
        return WORKER_BLOCK_CACHE[cache_key]

    block_bytes = COMMON.readMafBlockBytes(maf_fp, WORKER_MAF_COMPRESSION, entry["offset_start"], entry["offset_end"])
    block_text = block_bytes.decode("utf-8", errors="replace")
    WORKER_BLOCK_CACHE[cache_key] = block_text
    if len(WORKER_BLOCK_CACHE) > WORKER_BLOCK_CACHE_MAX:
        WORKER_BLOCK_CACHE.popitem(last=False)
    return block_text


def findOverlappingEntries(scaffold, bed_start, bed_end, index, profile_state=None):
    """
    Returns the list of index entries for `scaffold` that overlap
    [bed_start, bed_end), in ascending ref_start order. Shared by real-time
    lookup (fetchByRegion) and by prefetchBlockCache's upfront scan.
    """
    if scaffold not in index:
        return None

    scaffold_index = index[scaffold]
    candidate_idx = bisect.bisect_left(scaffold_index["starts"], bed_start)
    if candidate_idx > 0:
        candidate_idx -= 1

    overlapping = []
    for entry in scaffold_index["entries"][candidate_idx:]:
        if profile_state is not None:
            profile_state["candidate_entries"] += 1
        block_ref_start = entry["ref_start"]
        block_ref_end = block_ref_start + entry["ref_length"]

        if block_ref_end <= bed_start:
            continue  # block before region
        if block_ref_start >= bed_end:
            break     # block after region

        if bed_start < block_ref_end and bed_end > block_ref_start:
            if profile_state is not None:
                profile_state["overlap_blocks"] += 1
            overlapping.append(entry)

    return overlapping


def iterRegionEntries(index_fp, scaffold, bed_start, bed_end, run_indices, runs, run_offsets, resume, state):
    """
    Streams the blocks overlapping `scaffold`:[bed_start, bed_end), walking each
    run of that scaffold in file order.

    Runs are bounded by their MAF byte range (from the scaffold index), NOT by
    index byte positions: findIndexOffsetForMafByte returns a valid place to
    *start* scanning, deliberately allowed to sit early, so it must never be
    treated as an exact boundary. Each record's own offset_start is compared
    against the run's MAF range instead, which is exact.

    `resume` maps run -> byte offset to restart from, so consecutive regions on
    a scaffold do not rescan a run from its beginning. Because a worker walks
    its regions in ascending coordinate order, every later region has
    start >= bed_start, so any record ending at or before bed_start is
    irrelevant to all of them -- making the first record ending after bed_start
    a safe resume point, recorded in state.

    Nothing is buffered: entries are yielded as they stream, so a region
    spanning an entire scaffold costs O(1) memory here rather than O(blocks).
    """
    new_resume = dict(resume)
    for run in run_indices:
        _run_scaffold, maf_start, maf_end = runs[run]
        scan_from = max(run_offsets[run], resume.get(run, 0))
        resume_set = False

        for record, record_offset in iterIndexRecordsFrom(index_fp, scan_from):
            rec_scaffold, ref_start, ref_length, offset_start, offset_end = record
            if offset_start >= maf_end:
                break                      # past this run in the MAF
            if offset_start < maf_start:
                continue                   # not yet into this run
            if rec_scaffold != scaffold:
                continue                   # defensive; a run is single-scaffold
            if ref_start + ref_length <= bed_start:
                continue                   # block ends before the region starts
            if not resume_set:
                new_resume[run] = record_offset
                resume_set = True
            if ref_start >= bed_end:
                break                      # ascending, so nothing further overlaps
            yield {
                "ref_start": ref_start,
                "ref_length": ref_length,
                "offset_start": offset_start,
                "offset_end": offset_end,
            }
    state["resume"] = new_resume


#############################################################################

def prefetchBlockCache(regions, index, maf_file, maf_compression, LOG):
    """
    For plain-gzip input: collects every block entry needed across ALL
    regions, reads each exactly once in strictly-ascending file order (never
    seeking backward), and returns a dict keyed the same way as
    WORKER_BLOCK_CACHE. Used to pre-seed that cache so fetchByRegion's
    lookups are always hits during actual region processing.
    """
    needed = {}
    for region in regions:
        entries = findOverlappingEntries(region["scaffold"], region["start"], region["end"], index)
        if not entries:
            continue
        for entry in entries:
            needed[(entry["offset_start"], entry["offset_end"])] = entry

    ordered_keys = sorted(needed.keys())
    LOG.info(f"Prefetching {len(ordered_keys)} distinct block(s) needed across all regions (gzip input).")

    cache = {}
    with COMMON.openMaf(maf_file, maf_compression, "rb") as maf_fp:
        for offset_start, offset_end in ordered_keys:
            block_bytes = COMMON.readMafBlockBytes(maf_fp, maf_compression, offset_start, offset_end)
            cache[(offset_start, offset_end)] = block_bytes.decode("utf-8", errors="replace")

    return cache


def initProfileState():
    return {
        "regions": 0,
        "candidate_entries": 0,
        "overlap_blocks": 0,
        "time_batch_total": 0.0,
        "time_region_total": 0.0,
        "time_index_scan": 0.0,
        "time_read_decode": 0.0,
        "time_trim": 0.0,
        "time_block_to_fasta": 0.0,
        "time_fasta_stitch": 0.0,
        "time_write_fasta": 0.0,
    }


def addProfile(profile_state, key, value):
    if profile_state is not None:
        profile_state[key] += value


def mafBlockToFasta(block_text, region, dedupe_mode="none", use_species_keys=False):
    """
    Converts a (trimmed) MAF block to multi-FASTA format. 
    Each FASTA header includes the species, chrom, strand, and the (possibly trimmed) coordinates.
    Optionally, include region/scaffold in headers.
    """
    fasta_lines = defaultdict(dict)
    lines = block_text.strip().splitlines()
    block_len = 0

    for line in lines:
        if line.startswith("s "):
            fields = line.split()
            src = fields[1]  # species.chrom
            species = speciesFromSrc(src)
            #chrom = ".".join(src.split(".")[1:]) if "." in src else src
            #sp = src.split(".")[0] if "." in src else src
            start = int(fields[2])
            size = int(fields[3])
            strand = fields[4]
            #srcSize = fields[5]
            seq = fields[6]
            block_len = len(seq)
            key = species if use_species_keys else src
            nongap = sum(1 for c in seq if c != "-")
            
            # Compute 1-based closed interval for clarity (as in FASTA tools)
            if strand == "+":
                end = start + size
            else:
                # For negative strand, coordinates can be reported as on "forward" chromosome (for clarity, as in MAF)
                end = start + size

            if key in fasta_lines and dedupe_mode == "most-seq":
                if nongap > fasta_lines[key]["nongap"]:
                    fasta_lines[key] = {'seq': seq, 'start': start, 'end': end, 'strand': strand, 'nongap': nongap}
            elif key not in fasta_lines:
                fasta_lines[key] = {'seq': seq, 'start': start, 'end': end, 'strand': strand, 'nongap': nongap}
            elif dedupe_mode == "none":
                # Preserve previous behavior when dedupe is off by keeping src keys unique.
                # If duplicate src appears, keep first occurrence.
                pass

    for key in list(fasta_lines.keys()):
        if "nongap" in fasta_lines[key]:
            del fasta_lines[key]["nongap"]

    return fasta_lines, block_len

#############################################################################

def writeFASTA(fasta_seqs, region, fasta_stream, BATCHLOG, fasta_header=False, verbose=False, warning_state=None):

    fasta_output = {}
    for sp, details in fasta_seqs.items():
        if fasta_header == "species-only":
            header = f">{speciesFromSrc(sp)}"
        else:
            if details['starts'] and details['ends']:
                region_start = min(details['starts'])
                region_end = max(details['ends'])
            else:
                region_start = region['start']
                region_end = region['end']
            strand = list(set(details['strands'])) if details['strands'] else ["."]
            
            if len(strand) == 1:
                region_strand = strand[0]
            else:
                region_strand = "."
                appendWarning(
                    warning_state,
                    "multiple-strands",
                    f"Multiple strands found for species {sp} in region {region['scaffold']}:{region['start']}-{region['end']}. Using '.' in header.",
                )

            if fasta_header == "species-coords":
                header = f">{sp}:{region_start}-{region_end}({region_strand})"
            elif fasta_header == "species-coords-id":
                if "id" in region and region["id"]:
                    id_str = f"id:{region['id']}"
                header = f">{sp}:{region_start}-{region_end}({region_strand}) {id_str}"

        fasta_stream.write(f"{header}\n{''.join(details['seq'])}\n")

#############################################################################

def trimMafBlock(block_text, bed_start, bed_end, BATCHLOG, verbose=False, warning_state=None):
    """
    Trims a MAF block to exactly the portion overlapping [bed_start, bed_end)
    on the reference sequence. Assumes the reference sequence is given in the
    first "s" line after the header.

    The MAF "s" line format:
        s <src> <start> <size> <strand> <srcSize> <aligned_sequence>

    Returns the trimmed block as a string, or None if no overlap occurs.
    """

    lines = block_text.splitlines()
    if len(lines) < 2:
        return None  # Invalid block
    trimmed_lines = []
    if lines[0].startswith("a"):
        trimmed_lines.append(lines[0])
    else:
        trimmed_lines.append("a")
    
    ref_line_found = False
    ref_col_start = None
    ref_col_end = None
    new_ref_start = None
    new_ref_size = None
    for line in lines[1:]:

        fields = line.split()

        if not fields or fields[0] != "s":
            trimmed_lines.append(line)
            continue

        if not ref_line_found:
            ref_line_found = True
            try:
                block_ref_start = int(fields[2])
                block_ref_size = int(fields[3])
            except ValueError:
                BATCHLOG.error("Error parsing reference coordinates in MAF block.")
            ref_seq = fields[6]
            # Determine overlap with the block.
            overlap_start = max(bed_start, block_ref_start)
            overlap_end = min(bed_end, block_ref_start + block_ref_size)
            if overlap_start >= overlap_end:
                return None  # No overlap.
            
            # FIXED: Map the overlap to alignment columns correctly
            current_ref = block_ref_start
            col_start = None
            col_end = None

            for i, char in enumerate(ref_seq):
                if char != '-':
                    # This is a real reference position
                    if current_ref >= overlap_start and col_start is None:
                        col_start = i
                    current_ref += 1
                    if current_ref >= overlap_end:  # Check AFTER incrementing
                        col_end = i + 1  # Include current position
                        break
                elif col_start is not None and col_end is None:
                    # We're in our target region and this is a gap - we'll include it
                    pass

            if col_start is None:
                return None
            if col_end is None:
                col_end = len(ref_seq)

            if col_start is not None:
                extracted_ref_bases = sum(1 for c in ref_seq[col_start:col_end] if c != '-')
                expected_bases = overlap_end - overlap_start
                if extracted_ref_bases != expected_bases:
                    appendWarning(
                        warning_state,
                        "trim-mismatch",
                        f"Expected {expected_bases} bases but extracted {extracted_ref_bases} for region {overlap_start}-{overlap_end}",
                    )

            ref_col_start = col_start
            ref_col_end = col_end       
            new_ref_start = overlap_start
            new_ref_size = sum(1 for c in ref_seq[ref_col_start:ref_col_end] if c != '-')
            new_ref_end = new_ref_start + new_ref_size
            new_fields = fields.copy()
            new_fields[2] = str(new_ref_start)
            new_fields[3] = str(new_ref_size)
            new_fields[6] = ref_seq[ref_col_start:ref_col_end]
            trimmed_lines.append(" ".join(new_fields))

        else:
            species_seq = fields[6]
            offset_bases = sum(1 for c in species_seq[:ref_col_start] if c != '-')

            trimmed_seq = species_seq[ref_col_start:ref_col_end]
            trimmed_size = sum(1 for c in trimmed_seq if c != '-')       

            original_start = int(fields[2])
            strand = fields[4]
            original_size = int(fields[3])
            new_start = original_start + offset_bases
            # if strand == '+':
            #     new_start = original_start + offset_bases
            # else:
            #     new_start = original_start + (original_size - offset_bases - trimmed_size)                

            new_fields = fields.copy()
            new_fields[2] = str(new_start)
            new_fields[3] = str(trimmed_size)
            new_fields[6] = trimmed_seq
            trimmed_lines.append(' '.join(new_fields))

    #print(f"DEBUG: bed_interval=[{bed_start},{bed_end}), block_ref=[{block_ref_start},{block_ref_start + block_ref_size}), extracted_cols=[{ref_col_start}:{ref_col_end}], ref_seq_sample='{ref_seq[ref_col_start:ref_col_end] if ref_col_start is not None else 'None'}'", file=sys.stderr)

    return "\n".join(trimmed_lines), [new_ref_start, new_ref_end, new_ref_size]

#############################################################################

def buildOutputPath(output_dir, scaffold, out_basename, ext, scaffold_subdirs):
    """
    Shared per-output-file path builder for block mode (fetchByRegion) and
    scaffold mode (fetchByScaffold/fetchScaffoldsSequential). The scaffold
    subdirectory itself is never created here -- callers must pre-create
    every needed one upfront (see run_fetch) before any of these paths are
    actually opened for writing.
    """
    if scaffold_subdirs:
        return os.path.join(output_dir, scaffold, out_basename + ext)
    return os.path.join(output_dir, out_basename + ext)

#############################################################################

def fetchByRegion(
    region,
    header,
    maf_fp,
    overlapping_entries,
    output,
    BATCHLOG,
    single_output=False,
    as_fasta=False,
    fasta_header=False,
    expected_species=None,
    fasta_dedupe="none",
    verbose=False,
    warning_state=None,
    profile_state=None,
    scaffold_subdirs=False,
):
    """
    Worker function to process a single BED region:
        - Opens the MAF file independently.
        - Finds overlapping blocks in the index for region["scaffold"].
        - For each overlapping block, fetches and trims the block to the 
        exact [region["start"], region["end"]) interval on the reference.
        - Writes the trimmed blocks to an output file, using region["output_basename"] as filename.
    Returns a message summarizing the work.
    """

    scaffold = region["scaffold"]
    bed_start = region["start"]
    bed_end = region["end"]
    out_basename = region["output_basename"]
    region_str = f"{scaffold}\t{bed_start}\t{bed_end}\t{out_basename}"
    region_timer_start = time.perf_counter() if profile_state is not None else None
    # Parse region details

    block_lengths = []  # Holds lengths of each block written
    block_stats = []  # Holds [new_ref_start, new_ref_end, new_ref_size] for each block
    total_ref_bases = 0 # Total ref bases across all blocks

    if as_fasta:
        fasta_seqs = defaultdict(dict);
        species_order = expected_species[:] if expected_species else []
        expected_species_set = set(expected_species) if expected_species else set()
        use_species_keys = bool(expected_species) or fasta_dedupe != "none"
        fill_cache = {}
    # For fasta output, hold sequences per species

    output_filename = buildOutputPath(output, scaffold, out_basename, ".fa" if as_fasta else ".maf", scaffold_subdirs)
    out_stream = None

    if single_output:
        current_blocks = []
    # Single output mode being developed !

    blocks_written = 0;

    if overlapping_entries is None:
        # Caller signals "this scaffold isn't in the index at all" by passing
        # None, rather than fetchByRegion holding an index to check against.
        appendWarning(
            warning_state,
            "missing-scaffold",
            f"{scaffold}:{bed_start}-{bed_end} No index entries for scaffold.",
        )
        summary = f"{region_str}\t0\t0\tNA\t0"
        return summary if not single_output else []

    blocks_written = 0

    scan_timer_start = time.perf_counter() if profile_state is not None else None
    # overlapping_entries is an ITERATOR, deliberately not a list: a single BED
    # region can span an entire scaffold (hundreds of millions of blocks on a
    # whole-genome MAF), so materializing its blocks would reintroduce an
    # O(blocks) blowup for one region. Trimmed output is written to out_stream
    # inside this loop, so MAF output stays O(1) in block count. (FASTA output
    # is inherently O(region length x species) -- fasta_seqs below accumulates
    # each species' sequence before writing.)
    for entry in overlapping_entries:
        try:
            read_timer_start = time.perf_counter() if profile_state is not None else None
            block_text = getCachedBlockText(maf_fp, entry)
            if profile_state is not None:
                addProfile(profile_state, "time_read_decode", time.perf_counter() - read_timer_start)
            #print(block_text.splitlines()[1])
        except Exception as e:
            BATCHLOG.error(f"Error fetching block: {e}")
            raise

        trim_timer_start = time.perf_counter() if profile_state is not None else None
        trimmed_result = trimMafBlock(
            block_text,
            bed_start,
            bed_end,
            BATCHLOG,
            verbose=verbose,
            warning_state=warning_state,
        )
        if profile_state is not None:
            addProfile(profile_state, "time_trim", time.perf_counter() - trim_timer_start)
        if trimmed_result is None:
            continue
        trimmed, trimmed_info = trimmed_result

        if not single_output and trimmed is not None:
            block_stats.append(trimmed_info)
            total_ref_bases += trimmed_info[2]

            if blocks_written == 0 and not as_fasta:
                out_stream = open(output_filename, "w", encoding="utf-8")
                out_stream.write(header)
                out_stream.write("## Extracted by mafutils fetch\n")
                out_stream.write("## Source MAF: " + os.path.basename(WORKER_MAF_FILE or "") + "\n")
                out_stream.write(f"## Reference region: {region_str}\n")

            if as_fasta:

                # Output as fasta
                fasta_block_timer_start = time.perf_counter() if profile_state is not None else None
                return_fasta_seqs, block_len = mafBlockToFasta(
                    trimmed,
                    region,
                    dedupe_mode=fasta_dedupe,
                    use_species_keys=use_species_keys
                )
                if profile_state is not None:
                    addProfile(profile_state, "time_block_to_fasta", time.perf_counter() - fasta_block_timer_start)
                #fasta_lines[src] = {'header': header, 'seq': seq, 'start': start, 'end': end, 'strand': strand}
                block_lengths.append(block_len)

                stitch_timer_start = time.perf_counter() if profile_state is not None else None
                if expected_species:
                    for sp in expected_species:
                        if sp not in return_fasta_seqs:
                            return_fasta_seqs[sp] = {
                                'seq': getFillString(fill_cache, "N", block_len),
                                'start': None,
                                'end': None,
                                'strand': None
                            }

                # For any new species, add to order and backfill
                for sp in return_fasta_seqs:
                    if sp not in species_order:
                        species_order.append(sp)
                    if sp not in fasta_seqs:
                        # Backfill for all previous blocks
                        fasta_seqs[sp]['seq'] = [getFillString(fill_cache, "-", l) for l in block_lengths[:-1]]
                        fasta_seqs[sp]['starts'] = []
                        fasta_seqs[sp]['ends'] = []
                        fasta_seqs[sp]['strands'] = []

                # After establishing all species, append current block or pad as needed
                for sp in species_order:
                    if sp in return_fasta_seqs:
                        seq = return_fasta_seqs[sp]['seq']
                    else:
                        fill_char = "N" if sp in expected_species_set else "-"
                        seq = getFillString(fill_cache, fill_char, block_len)
                    fasta_seqs[sp]['seq'].append(seq)
                    if sp in return_fasta_seqs:
                        if return_fasta_seqs[sp]['start'] is not None:
                            fasta_seqs[sp]['starts'].append(return_fasta_seqs[sp]['start'])
                        if return_fasta_seqs[sp]['end'] is not None:
                            fasta_seqs[sp]['ends'].append(return_fasta_seqs[sp]['end'])
                        if return_fasta_seqs[sp]['strand'] is not None:
                            fasta_seqs[sp]['strands'].append(return_fasta_seqs[sp]['strand'])
                if profile_state is not None:
                    addProfile(profile_state, "time_fasta_stitch", time.perf_counter() - stitch_timer_start)
            else:
                out_stream.write(trimmed + "\n")
            blocks_written += 1
        elif single_output and trimmed is not None:
            if as_fasta:
                return_fasta_seqs, _ = mafBlockToFasta(
                    trimmed,
                    region,
                    dedupe_mode=fasta_dedupe,
                    use_species_keys=use_species_keys
                )
                current_blocks.append(return_fasta_seqs)
            else:
                current_blocks.append(trimmed + "\n")

    if as_fasta and not single_output and blocks_written > 0:
        out_stream = open(output_filename, "w", encoding="utf-8")
        # Write all fasta sequences to the output
        write_timer_start = time.perf_counter() if profile_state is not None else None
        writeFASTA(
            fasta_seqs,
            region,
            out_stream,
            BATCHLOG,
            fasta_header=fasta_header,
            verbose=verbose,
            warning_state=warning_state,
        )
        if profile_state is not None:
            addProfile(profile_state, "time_write_fasta", time.perf_counter() - write_timer_start)

    if not blocks_written:
        appendWarning(
            warning_state,
            "no-overlap",
            f"{scaffold}:{bed_start}-{bed_end} No overlapping blocks found.",
        )

    if not single_output:
        if out_stream is not None:
            out_stream.close()
        # --- BEGIN SUMMARY REPORT ---
        # Collect region info
        block_stats.sort()
        
        interblock_spaces = [
            block_stats[i][0] - block_stats[i-1][1]
            for i in range(1, len(block_stats))
        ] if len(block_stats) > 1 else []

        num_blocks = len(block_stats)
        blocks_length = sum(info[2] for info in block_stats)
        space_str = str(interblock_spaces) if interblock_spaces else "NA"
        if profile_state is not None:
            profile_state["regions"] += 1
            addProfile(profile_state, "time_index_scan", time.perf_counter() - scan_timer_start)
            addProfile(profile_state, "time_region_total", time.perf_counter() - region_timer_start)
        summary = (f"{region_str}\t{num_blocks}\t{blocks_length}\t{space_str}\t{len(species_order) if as_fasta else 'NA'}")
        return summary

    else:
        if profile_state is not None:
            profile_state["regions"] += 1
            addProfile(profile_state, "time_index_scan", time.perf_counter() - scan_timer_start)
            addProfile(profile_state, "time_region_total", time.perf_counter() - region_timer_start)
        return current_blocks;

#############################################################################

def fetchByBatch(
    batch,
    batch_num,
):

    BATCHLOG = logging.getLogger("maf_fetch_logger")
    plural = "s" if len(batch) > 1 else ""
    BATCHLOG.info(f"Processing batch {batch_num} with {len(batch)} region{plural}")
    BATCHLOG.debug(f">> (first: {batch[0]['scaffold']}:{batch[0]['start']}-{batch[0]['end']}, last: {batch[-1]['scaffold']}:{batch[-1]['start']}-{batch[-1]['end']})")
    # Initialize batch-specific logger

    maf_fp = WORKER_MAF_FP
    if maf_fp is None:
        BATCHLOG.error(f"Batch {batch_num}: Worker MAF handle is not initialized.")
        raise RuntimeError("Worker MAF handle is not initialized.")

    batch_results = [None] * len(batch)
    region_num = 0
    no_output_regions = 0
    written_regions = 0
    warning_state = {"count": 0, "counts": {}, "messages": [] if WORKER_VERBOSE else None}
    profile_state = initProfileState() if WORKER_PROFILE else None
    batch_timer_start = time.perf_counter() if WORKER_PROFILE else None

    # Regions arrive already sorted into INDEX order by the parent, which is
    # what lets this walk the index forward once. Re-sorting here (as this used
    # to, by scaffold *name*) would break that: index scaffold order is MAF file
    # order, not alphabetical.
    index_fp = open(WORKER_INDEX_FILE, "r", encoding="utf-8")
    scaffold_to_runs, runs, run_offsets = WORKER_SCAFFOLD_RUNS
    # Per-run resume points, so consecutive regions on a scaffold continue
    # forward through the index instead of rescanning from the run's start.
    resume_by_scaffold = {}

    try:
        for batch_order, (result_idx, region) in enumerate(enumerate(batch), start=1):
            region_num += 1

            batch_str = f" [batch {batch_num}.{batch_order}]"
            BATCHLOG.debug(f">>>{batch_str} Region {region['scaffold']}:{region['start']}-{region['end']}")

            scaffold = region["scaffold"]
            run_indices = scaffold_to_runs.get(scaffold)
            if not run_indices:
                entries = None       # signals "scaffold absent from the index"
                scan_state = None
            else:
                scan_state = {}
                entries = iterRegionEntries(
                    index_fp,
                    scaffold,
                    region["start"],
                    region["end"],
                    run_indices,
                    runs,
                    run_offsets,
                    resume_by_scaffold.get(scaffold, {}),
                    scan_state,
                )

            region_result = fetchByRegion(
                region,
                WORKER_HEADER,
                maf_fp,
                entries,
                WORKER_OUTPUT,
                BATCHLOG,
                as_fasta=WORKER_AS_FASTA,
                fasta_header=WORKER_FASTA_HEADER,
                expected_species=WORKER_EXPECTED_SPECIES,
                fasta_dedupe=WORKER_FASTA_DEDUPE,
                verbose=WORKER_VERBOSE,
                warning_state=warning_state,
                profile_state=profile_state,
                scaffold_subdirs=WORKER_SCAFFOLD_SUBDIRS,
            )

            if scan_state and "resume" in scan_state:
                # Resume the next region's scan from the first block that could
                # still matter. If fetchByRegion returned before exhausting the
                # iterator, "resume" is simply absent and the previous (earlier,
                # conservative) offsets are kept -- correct, just more rescanning.
                resume_by_scaffold[scaffold] = scan_state["resume"]

            batch_results[result_idx] = region_result
            if not WORKER_SINGLE_OUTPUT:
                # Field 4 is n.overlapping.blocks (see summary_headers). This
                # used to read field 1, which is the region's START coordinate
                # -- so every region beginning at coordinate 0 was counted as
                # "no output" despite having been extracted fine, inflating
                # zero_overlap_regions and tripping the zero-overlap failure
                # threshold. A single-region BED starting at 0 always failed.
                fields = region_result.split("\t")
                if len(fields) >= 5:
                    try:
                        if int(fields[4]) == 0:
                            no_output_regions += 1
                        else:
                            written_regions += 1
                    except ValueError:
                        pass
    finally:
        index_fp.close()

    if profile_state is not None:
        profile_state["time_batch_total"] = time.perf_counter() - batch_timer_start

    return {
        "results": batch_results,
        "processed_regions": len(batch_results),
        "zero_overlap_regions": no_output_regions,
        "no_output_regions": no_output_regions,
        "batch_num": batch_num,
        "written_regions": written_regions,
        "warning_count": warning_state["count"],
        "warning_counts": warning_state["counts"],
        "warning_messages": warning_state["messages"],
        "profile": profile_state,
    }

#############################################################################

def fetchByScaffold(scaffold, start_end, maf_file, maf_header, maf_compression, out_dir, LOG, scaffold_subdirs=False):
    """
    Worker function to extract one scaffold from the MAF file.
    start_end is a tuple (start_byte, end_byte).
    """
    start, end = start_end
    output_path = buildOutputPath(out_dir, scaffold, scaffold, ".maf", scaffold_subdirs)

    try:
        with COMMON.openMaf(maf_file, maf_compression, "rb") as mfp, open(output_path, "wb") as outfp:
            LOG.info(f">>> Scaffold {scaffold}");
            outfp.write(maf_header.encode("utf-8"))
            # Streamed in bounded chunks: a scaffold can be hundreds of GB,
            # far too large to materialize as one bytes object.
            written = COMMON.copyMafRangeToStream(mfp, maf_compression, start, end, outfp)
    except Exception as e:
        # repr(), plus the traceback, because some of the exceptions that
        # actually occur here have an empty str() -- MemoryError being the
        # one that made a real failure log as a blank message.
        LOG.error(f"{scaffold}: FAILED to extract: {e!r}")
        LOG.debug("Traceback for %s:\n%s", scaffold, traceback.format_exc())
        return {"scaffold": scaffold, "output_path": output_path, "ok": False, "error": repr(e)}

    return {"scaffold": scaffold, "output_path": output_path, "ok": True, "bytes_written": written}


def fetchScaffoldsSequential(ordered_scaffolds, index, maf_file, maf_header, maf_compression, out_dir, LOG, scaffold_subdirs=False):
    """
    Extracts multiple scaffolds using a single open MAF handle, in the given
    (ascending file-offset) order. Used for gzip input: reusing one handle
    and never seeking backward avoids the redundant-decompression cost that
    reopening the file per scaffold (as fetchByScaffold does) would incur.
    """
    results = []
    with COMMON.openMaf(maf_file, maf_compression, "rb") as mfp:
        for scaffold in ordered_scaffolds:
            start, end = index[scaffold]
            output_path = buildOutputPath(out_dir, scaffold, scaffold, ".maf", scaffold_subdirs)
            try:
                LOG.info(f">>> Scaffold {scaffold}");
                with open(output_path, "wb") as outfp:
                    outfp.write(maf_header.encode("utf-8"))
                    # Streamed in bounded chunks -- see fetchByScaffold.
                    written = COMMON.copyMafRangeToStream(mfp, maf_compression, start, end, outfp)
            except Exception as e:
                LOG.error(f"{scaffold}: FAILED to extract: {e!r}")
                LOG.debug("Traceback for %s:\n%s", scaffold, traceback.format_exc())
                results.append({"scaffold": scaffold, "output_path": output_path, "ok": False, "error": repr(e)})
                continue
            results.append({"scaffold": scaffold, "output_path": output_path, "ok": True, "bytes_written": written})
    return results


#############################################################################

def run_fetch(args, cmdline="mafutils fetch"):

    if not args.single_output:
        os.makedirs(args.output, exist_ok=True);
    # Create the output directory before deciding where the log goes -- the
    # log path check below needs args.output to already exist, since that's
    # the whole point of checking os.path.isdir() rather than just always
    # joining onto it.

    logfilename = os.path.join(args.output, "maf_fetch.log") if os.path.isdir(args.output) else "maf_fetch.log"
    maf_fetch_logger = LOGINIT.configureLogging(log_level="INFO", log_verbosity="BOTH", log_filename=logfilename, logger_name="maf_fetch_logger", overwrite_log_file=True)
    LOG = logging.getLogger(maf_fetch_logger)
    # Set up logging

    LOG.info(f"mafutils fetch called as: {cmdline}");
    LOG.info("-" * 40);
    for arg, value in vars(args).items():
        valstr = str(value)
        if len(valstr) > 80:
            valstr = valstr[:77] + "..."
        LOG.info(f"{arg:20} : {valstr}")
    LOG.info("-" * 40 )
    # Log the command line arguments

    if args.mode not in ("block", "scaffold"):
        LOG.error(f"Invalid mode: '{args.mode}'. Must be 'block' or 'scaffold'.")
        sys.exit(1)
    # Validate mode

    if args.scaffold_subdirs and args.single_output:
        LOG.error("--scaffold-subdirs cannot be used with --single-output.")
        sys.exit(1)
    # --single-output collects blocks into one combined file and never uses
    # per-region output_basename/output_filename at all, so it doesn't
    # compose with grouping per-region files into scaffold subfolders.
    # if args.max_no_overlap_regions < -1:
    #     LOG.error("--max-no-overlap-regions must be >= -1.")
    #     sys.exit(1)
    # if args.max_no_overlap_fraction < 0.0 or args.max_no_overlap_fraction > 1.0:
    #     LOG.error("--max-no-overlap-fraction must be between 0 and 1.")
    #     sys.exit(1)

    maf_compression = COMMON.detectCompression(args.maf_file);
    if maf_compression not in ("none", "gz", "bgzip"):
        LOG.error(f"Unsupported MAF compression: {maf_compression}")
        sys.exit(1)

    index_file = args.index_file
    if index_file is None:
        index_file = (
            COMMON.deriveScaffoldIndexPath(args.maf_file)
            if args.mode == "scaffold"
            else COMMON.deriveBlockIndexPath(args.maf_file)
        )
        if not os.path.isfile(index_file):
            LOG.error(
                f"No index given and none found at default location ({index_file}). "
                f"Run `mafutils index` first."
            )
            sys.exit(1)
        LOG.info(f"Using index at default location: {index_file}")

    LOG.info(f"Parsing index file.... {index_file}");
    COMMON.validateIndexHeader(COMMON.readIndexHeader(index_file), args.maf_file, maf_compression, LOG, strict=args.verify_hash)

    # Scaffold mode's index is one line per scaffold (trivially small), so it is
    # still loaded. Block mode streams its index instead -- see below.
    index = parseIndex(index_file, LOG, args.mode) if args.mode == "scaffold" else None

    scaffold_runs = None
    scaffold_first_run = {}
    if args.mode == "block":
        scaffold_index_file = COMMON.deriveScaffoldIndexPath(args.maf_file)
        if not os.path.isfile(scaffold_index_file):
            LOG.error(
                f"Block mode needs the scaffold index ({scaffold_index_file}) to order regions "
                f"the same way the block index is ordered, but it was not found. "
                f"Run `mafutils index` to create it."
            )
            sys.exit(1)

        # The two indexes must come from the same `mafutils index` run: block
        # mode locates blocks using byte ranges recorded in the scaffold index,
        # so a mismatched pair silently drops regions (an off-by-one boundary
        # is enough to skip every run's first block). Both files stamp the
        # MAF's size/mtime/hash in their header, so compare those -- the same
        # cross-check `mafutils validate` performs.
        block_header = COMMON.readIndexHeader(index_file)
        scaffold_header = COMMON.readIndexHeader(scaffold_index_file)
        if block_header is None or scaffold_header is None or block_header != scaffold_header:
            LOG.error(
                f"The block index ({index_file}) and scaffold index ({scaffold_index_file}) "
                f"do not come from the same `mafutils index` run, so their byte offsets cannot "
                f"be trusted together. Rebuild both with `mafutils index`."
            )
            LOG.error(f"  block index header:    {block_header}")
            LOG.error(f"  scaffold index header: {scaffold_header}")
            sys.exit(1)

        runs = readScaffoldRuns(scaffold_index_file)
        # One binary search per run, once, to get a starting point for each
        # run's records. These are scan hints, not exact bounds -- the run's
        # MAF byte range is what actually delimits it.
        run_offsets = computeRunIndexOffsets(index_file, runs)
        scaffold_to_runs = {}
        for i, (scaffold, _s, _e) in enumerate(runs):
            scaffold_to_runs.setdefault(scaffold, []).append(i)
            scaffold_first_run.setdefault(scaffold, i)
        scaffold_runs = (scaffold_to_runs, runs, run_offsets)
        LOG.info(
            f"Loaded {len(runs)} scaffold run(s) covering {len(scaffold_to_runs)} scaffold(s) "
            f"from {scaffold_index_file}"
        )

    LOG.info(f"Parsing BED file...... {args.bed_file}");
    regions = parseBed(args.bed_file, LOG, args.mode);

    expected_species = parseExpectedSpecies(args)
    if expected_species:
        LOG.info(f"Loaded {len(expected_species)} expected species for FASTA missing-species filling.")

    LOG.info(f"Getting MAF header.... {args.maf_file}");
    maf_header = getMAFHeader(args.maf_file, maf_compression);

    ##############################
    # SCAFFOLD MODE
    ##############################

    if args.mode == "scaffold":
        if args.single_output:
            LOG.error("--single-output cannot be used in scaffold mode.");
            sys.exit(1)

        if args.fasta:
            LOG.error("FASTA output not supported in scaffold mode.")
            sys.exit(1)
        if expected_species:
            LOG.error("--expected-species/--expected-species-file can only be used in block mode with --fasta.")
            sys.exit(1)
        if args.fasta_dedupe != "none":
            LOG.error("--fasta-dedupe can only be used in block mode with --fasta.")
            sys.exit(1)

        LOG.info(f"Running in SCAFFOLD mode with BED + region index");

        # Parse the BED file to get a set of scaffolds to extract
        scaffold_set = set(region["scaffold"] for region in regions);
        for scaffold in scaffold_set:
            if scaffold not in index:
                LOG.error(f"Scaffold '{scaffold}' not found in index.")
                sys.exit(1)
        LOG.info(f"Extracting {len(scaffold_set)} scaffolds from scaffold index: {scaffold_set}");

        if args.scaffold_subdirs:
            # Pre-create upfront in the main process, same rationale as
            # block mode below -- avoids any per-worker/cross-process race.
            for scaffold in scaffold_set:
                os.makedirs(os.path.join(args.output, scaffold), exist_ok=True)

        # Process scaffolds in ascending file-offset order; for gzip this is
        # what lets a single reused handle avoid ever seeking backward.
        ordered_scaffolds = sorted(scaffold_set, key=lambda s: index[s][0])

        scaffold_results = []
        if maf_compression == "gz":
            if args.processes > 1:
                LOG.warning(
                    "Parallel processing requires random access into the MAF, which is inefficient on "
                    "gzip-compressed files; --processes will be ignored. (Use a bgzip-compressed MAF "
                    "for real parallel speedup on compressed input.)"
                )
            scaffold_results = fetchScaffoldsSequential(ordered_scaffolds, index, args.maf_file, maf_header, maf_compression, args.output, LOG, scaffold_subdirs=args.scaffold_subdirs)
        else:
            # Extract from MAF using the region index for matching scaffolds
            with ProcessPoolExecutor(max_workers=args.processes) as executor:
                futures = []
                for scaffold in ordered_scaffolds:
                    start, end = index[scaffold]
                    futures.append(executor.submit(
                        fetchByScaffold,
                        scaffold,
                        (start, end),
                        args.maf_file,
                        maf_header,
                        maf_compression,
                        args.output,
                        LOG,
                        args.scaffold_subdirs,
                    ))
                for future in futures:
                    scaffold_results.append(future.result())

        # Only report "Wrote" for extractions that actually produced data --
        # never for one that raised or came back empty.
        for result in scaffold_results:
            if result["ok"] and result["bytes_written"] > 0:
                LOG.info(f"{result['output_path']}: Wrote {result['scaffold']} ({result['bytes_written']} bytes)")

        # Any scaffold that failed to extract must fail the run. Previously
        # these errors were logged and then reported as "Wrote <scaffold>"
        # anyway, so fetch exited 0 with a 0-byte output file and downstream
        # consumers proceeded on silently-corrupt state.
        failed = [r for r in scaffold_results if not r["ok"]]
        if failed:
            LOG.error(
                "Failed to extract %d of %d scaffold(s): %s",
                len(failed),
                len(scaffold_results),
                ", ".join(r["scaffold"] for r in failed),
            )
            sys.exit(1)

        empty = [r for r in scaffold_results if r["ok"] and r["bytes_written"] == 0]
        if empty:
            # No exception, but nothing came back for the requested range --
            # e.g. a bad/stale index offset. Still not a success.
            LOG.error(
                "Extracted 0 alignment bytes for %d scaffold(s): %s. Check that the index matches this MAF.",
                len(empty),
                ", ".join(r["scaffold"] for r in empty),
            )
            sys.exit(1)

        return;  # Done with scaffold mode

    ##############################
    # BLOCK MODE (default)
    ##############################

    LOG.info(f"Running in BLOCK mode");
    if expected_species and not args.fasta:
        LOG.error("--expected-species/--expected-species-file require --fasta.")
        sys.exit(1)
    if args.fasta_dedupe != "none" and not args.fasta:
        LOG.error("--fasta-dedupe requires --fasta.")
        sys.exit(1)

    effective_processes = args.processes
    prefetch_cache = None
    if maf_compression == "gz":
        if args.processes > 1:
            LOG.warning(
                "Parallel processing requires random access into the MAF, which is inefficient on "
                "gzip-compressed files; --processes will be ignored. (Use a bgzip-compressed MAF "
                "for real parallel speedup on compressed input.)"
            )
        effective_processes = 1
        # No prefetch pass any more. Regions are sorted into index order below
        # and each worker walks the index forward, so blocks are read in
        # ascending file order for EVERY compression type -- which is the
        # property prefetchBlockCache existed to give gzip, now obtained
        # structurally instead of by decoding every needed block into RAM
        # first (a real run reported "Prefetching 1031475 distinct block(s)",
        # i.e. its own O(needed blocks) memory blowup). Reuse of a block shared
        # by neighbouring regions is still handled, by the bounded
        # WORKER_BLOCK_CACHE LRU -- and sorting makes those regions adjacent,
        # so a small cache captures it.

    # Sort regions into INDEX order (scaffold order as it appears in the MAF,
    # then coordinate), so the block index can be streamed forward instead of
    # loaded into memory. Regions are the cheap side of this: ~979k regions vs
    # ~233M blocks on a whole-genome MAF.
    unknown_rank = len(scaffold_first_run)
    regions.sort(key=lambda r: (scaffold_first_run.get(r["scaffold"], unknown_rank), r["start"], r["end"]))

    num_regions = len(regions);
    # One batch per worker: each streams its own span of the index. Splitting
    # by region count (not by scaffold) keeps parallelism independent of how
    # many scaffolds there are and of how wildly their sizes differ.
    n_batches = max(1, min(effective_processes, num_regions))
    batch_size = (num_regions + n_batches - 1) // n_batches
    LOG.info(f"Using batch size of {batch_size} regions for {num_regions} total regions with {effective_processes} processes.");
    batches = list(chunker(regions, size=batch_size))
    LOG.info(f"Divided {len(regions)} regions into {len(batches)} batches of up to {batch_size} regions each.");


    # Region batching for parallel processing

    if args.single_output:
        if args.output == "." or os.path.isdir(args.output):
            output_file = "maf-fetch.maf"
        else:
            if os.path.isdir(args.output):
                LOG.error("--single-output cannot be used with --outdir. Use current directory only.");
                sys.exit(1)
            output_file = args.output
        LOG.info(f"Using single output file: {output_file}")
    ## Single output mode being developed !

    # Pre-assign output basenames for regions.
    # For regions missing a 4th column (basename), assign a unique counter per scaffold.
    region_counter = {}
    for region in regions:
        scaffold = region["scaffold"]
        start = region["start"]
        end = region["end"]
        basename_mode = args.basename

        if basename_mode == "id":
            if region.get("id"):
                region["output_basename"] = region["id"]
            else:
                LOG.error(f"Basename mode set to 'id', but '{region}' lacks an ID (4th column).");
        elif basename_mode == "count":
            count = region_counter.get(scaffold, 0) + 1
            region_counter[scaffold] = count
            region["output_basename"] = f"{scaffold}.{count}"
        else: # basename_mode == "coords":
            region["output_basename"] = f"{scaffold}-{start}-{end}"

    if args.scaffold_subdirs:
        # Pre-create every needed scaffold subdirectory upfront, in the main
        # process, mirroring the single os.makedirs(args.output, ...) above --
        # block-mode writes happen inside ProcessPoolExecutor workers, and
        # nothing per-worker creates directories today, so doing this here
        # avoids needing any cross-process race handling at write time.
        for scaffold in {region["scaffold"] for region in regions}:
            os.makedirs(os.path.join(args.output, scaffold), exist_ok=True)

    info_outfile = os.path.join(args.output, "maf_fetch_summary.tsv")

    # if args.fasta_header and not args.fasta:
    #     LOG.warning("--fasta-header is only used with --fasta output. Ignoring.");

    # Process each batch in parallel.
    results = [];
    total_regions_reported = 0
    zero_overlap_regions = 0
    fail_fast_triggered = False
    fail_fast_message = None
    no_overlap_threshold_warned = False
    missing_scaffold_regions = 0
    profile_totals = initProfileState() if args.profile else None
    profiled_batches = 0
    with ProcessPoolExecutor(
        max_workers=effective_processes,
        initializer=initBatchWorker,
        initargs=(
            maf_header,
            args.maf_file,
            maf_compression,
            None,   # block mode streams the index; nothing to hand to workers
            args.output,
            args.single_output,
            args.fasta,
            args.fasta_header,
            expected_species,
            args.fasta_dedupe,
            args.verbose,
            args.profile,
            prefetch_cache,
            args.scaffold_subdirs,
            index_file,
            scaffold_runs,
        ),
    ) as executor, open(info_outfile, "w") as info_out:
        summary_headers = ["scaffold", "start", "end", "basename", "n.overlapping.blocks", "block.lengths", "interblock.distances", "n.sequences"]
        info_out.write("\t".join(summary_headers) + "\n")

        futures = {}
        for batch_num, batch in enumerate(batches, start=1):
            future = executor.submit(
                fetchByBatch,
                batch,
                batch_num,
            )
            futures[future] = batch_num

        while futures:
            done, _pending = wait(list(futures.keys()), return_when=FIRST_COMPLETED)
            for future in done:
                batch_num = futures.pop(future)
                result = future.result()
                if args.profile and result["profile"] is not None:
                    profiled_batches += 1
                    for key, value in result["profile"].items():
                        profile_totals[key] += value

                if not args.single_output:
                    for r in result["results"]:
                        info_out.write(r + "\n")
                    total_regions_reported += result["processed_regions"]
                    zero_overlap_regions += result["zero_overlap_regions"]
                    missing_scaffold_regions += result["warning_counts"].get("missing-scaffold", 0)

                    if result["warning_count"] > 0 and args.verbose:
                        for warning_message in result["warning_messages"]:
                            LOG.warning(warning_message)

                    zero_overlap_fraction_final_floor = zero_overlap_regions / num_regions if num_regions else 0.0

                    summary_log = LOG.warning if (
                        result["warning_count"] > 0 or result["no_output_regions"] > 0
                    ) else LOG.info

                    summary_log(
                        "Completed batch %d: %d total / %d written / %d no-output / warnings: %s",
                        result["batch_num"],
                        result["processed_regions"],
                        result["written_regions"],
                        result["no_output_regions"],
                        formatWarningCounts(result["warning_counts"]),
                    )

                    # Advisory only -- regions that overlap no alignment block
                    # are a normal outcome when fetching many intervals, so
                    # they warn rather than abort. (The genuinely diagnostic
                    # case, *every* region finding nothing, is still fatal --
                    # see the end-of-run check.) Warn once, not per batch.
                    if not no_overlap_threshold_warned:
                        if zero_overlap_regions > ADVISORY_NO_OVERLAP_REGIONS:
                            no_overlap_threshold_warned = True
                            LOG.warning(
                                "Zero-overlap regions (%d) exceeded the advisory max (%d); continuing.",
                                zero_overlap_regions,
                                ADVISORY_NO_OVERLAP_REGIONS,
                            )
                        elif zero_overlap_fraction_final_floor > ADVISORY_NO_OVERLAP_FRACTION:
                            no_overlap_threshold_warned = True
                            LOG.warning(
                                "Zero-overlap fraction is at least %.6f, above the advisory max "
                                "(%.6f); continuing.",
                                zero_overlap_fraction_final_floor,
                                ADVISORY_NO_OVERLAP_FRACTION,
                            )
                else:
                    results.append(result["results"])

            if fail_fast_triggered:
                for pending_future in futures:
                    pending_future.cancel()
                break

    if fail_fast_triggered:
        LOG.error(fail_fast_message)
        sys.exit(2)

    if args.profile and profile_totals is not None and profiled_batches > 0:
        LOG.info("Profile summary across %d batch(es):", profiled_batches)
        LOG.info(
            "Profile regions=%d candidate_entries=%d overlap_blocks=%d",
            profile_totals["regions"],
            profile_totals["candidate_entries"],
            profile_totals["overlap_blocks"],
        )
        LOG.info(
            "Profile time_batch_total=%.3fs time_region_total=%.3fs time_index_scan=%.3fs "
            "time_read_decode=%.3fs time_trim=%.3fs time_block_to_fasta=%.3fs "
            "time_fasta_stitch=%.3fs time_write_fasta=%.3fs",
            profile_totals.get("time_batch_total", 0.0),
            profile_totals["time_region_total"],
            profile_totals["time_index_scan"],
            profile_totals["time_read_decode"],
            profile_totals["time_trim"],
            profile_totals["time_block_to_fasta"],
            profile_totals["time_fasta_stitch"],
            profile_totals["time_write_fasta"],
        )

    if not args.single_output and missing_scaffold_regions > 0:
        # Advisory, like the other non-overlap outcomes: fetch is normally
        # pointed at many intervals and a BED may legitimately carry scaffolds
        # this MAF doesn't have. Still worth calling out prominently, since the
        # usual cause is a naming mismatch (e.g. "chr1" vs "1") or the wrong
        # index, and every region on that scaffold silently yields nothing.
        LOG.warning(
            "%d region(s) reference a scaffold that is not in the index at all. If that is "
            "unexpected, check that the BED's scaffold names match the MAF's (and that this is "
            "the right index).",
            missing_scaffold_regions,
        )

    if not args.single_output and total_regions_reported > 0 and zero_overlap_regions > 0:
        zero_overlap_fraction = zero_overlap_regions / total_regions_reported
        LOG.warning(
            "%d of %d regions had no overlapping MAF blocks (%.6f).",
            zero_overlap_regions,
            total_regions_reported,
            zero_overlap_fraction,
        )
        # Advisory too. A region overlapping no alignment block is normal data,
        # not a malfunction -- fetch is typically pointed at many intervals, and
        # a one-region BED that happens not to overlap is the same situation as
        # "all regions" failing. Genuine misuse is caught earlier and loudly:
        # index/MAF hash+size mismatch (validateIndexHeader), a block/scaffold
        # index pair from different runs, and per-scaffold extraction failures.
        if zero_overlap_regions == total_regions_reported:
            LOG.warning("No regions overlapped any MAF block.")
        # The count/fraction thresholds are advisory: some regions not
        # overlapping any block is expected when fetching many intervals.
        if (
            ADVISORY_NO_OVERLAP_REGIONS >= 0
            and zero_overlap_regions > ADVISORY_NO_OVERLAP_REGIONS
        ):
            LOG.warning(
                "Zero-overlap regions (%d) exceeded the advisory max (%d).",
                zero_overlap_regions,
                ADVISORY_NO_OVERLAP_REGIONS,
            )
        if zero_overlap_fraction > ADVISORY_NO_OVERLAP_FRACTION:
            LOG.warning(
                "Zero-overlap fraction (%.6f) exceeded the advisory max (%.6f).",
                zero_overlap_fraction,
                ADVISORY_NO_OVERLAP_FRACTION,
            )

    # if args.single_output:
    #     with open(output_file, "w", encoding="utf-8") as out_stream:
    #         if not args.fasta:
    #             out_stream.write(maf_header)  # Write header to single output file

    #         total_blocks = 0
    #         for block_list in results:
    #             if block_list:  # block_list is now a list of strings
    #                 for block in block_list:
    #                     out_stream.write(block)
    #                     total_blocks += 1

    #     LOG.info(f"Single output file written: {output_file} ({total_blocks} blocks)")


def fetch_command(
    maf_file: Annotated[str, typer.Argument(help="Input MAF file (.maf, .maf.gz, or bgzip-compressed .maf)")],
    bed_file: Annotated[str, typer.Argument(help="BED file with regions or scaffold names to extract")],
    index_file: Annotated[
        Optional[str],
        typer.Option(
            "--index", "-i",
            help="Index file (block-level or scaffold-level, matching --mode). Required -- if omitted, looked up at <MAF_FILE>.block.idx or <MAF_FILE>.scaffold.idx by default; errors if not found there.",
        ),
    ] = None,
    basename: Annotated[BasenameMode, typer.Option("--basename", "-b", help="Basename strategy: 'id' (BED 4th col if present), 'coords' (scaffold-start-end), or 'count' (numbered per scaffold)")] = BasenameMode.coords,
    output: Annotated[str, typer.Option("--output", "-o", help="Output directory (default: current directory); if --single-output is used, this should instead be a filename and will default to maf-fetch.maf in the current directory.")] = ".",
    fasta: Annotated[bool, typer.Option("--fasta", "-f", help="Output region(s) in FASTA format instead of MAF.")] = False,
    fasta_header: Annotated[FastaHeaderMode, typer.Option("--fasta-header", "-fh", help="Controls the FASTA header format: 'species-coords-id' (default, includes species, coordinates, and region ID if present),'species-coords' (species and coordinates only), or 'species-only' (just the species name).")] = FastaHeaderMode.species_coords,
    expected_species: Annotated[str, typer.Option("--expected-species", help="Comma-separated species list expected in FASTA output; missing species are filled per block with Ns.")] = "",
    expected_species_file: Annotated[str, typer.Option("--expected-species-file", help="File with one expected species name per line for FASTA missing-species filling.")] = "",
    fasta_dedupe: Annotated[FastaDedupeMode, typer.Option("--fasta-dedupe", help="When outputting FASTA, collapse duplicate species per block; 'most-seq' keeps the copy with most non-gap bases.")] = FastaDedupeMode.none,
    processes: Annotated[int, typer.Option("--processes", "-p", help="Number of parallel processes to use (default: 1)")] = 1,
    mode: Annotated[FetchMode, typer.Option("--mode", "-m", help="Mode: 'block' to trim by regions, 'scaffold' to extract whole scaffolds (default: block)")] = FetchMode.block,
    scaffold_subdirs: Annotated[bool, typer.Option("--scaffold-subdirs", help="Group output files into subfolders named by reference scaffold (<output>/<scaffold>/<basename>) instead of one flat directory.")] = False,
    single_output: Annotated[bool, typer.Option("--single-output", hidden=True)] = False,
    verbose: Annotated[bool, typer.Option("--verbose", help="Print every warning line after each batch completes.")] = False,
    profile: Annotated[bool, typer.Option("--profile", help="Log aggregate timing breakdowns for internal fetch steps.")] = False,
    verify_hash: Annotated[bool, typer.Option("--verify-hash", help="Verify the index's stored content hash against the MAF file (reads the whole file).")] = False,
) -> None:
    args = SimpleNamespace(
        maf_file=maf_file,
        index_file=index_file,
        bed_file=bed_file,
        basename=basename.value,
        output=output,
        fasta=fasta,
        fasta_header=fasta_header.value,
        expected_species=expected_species,
        expected_species_file=expected_species_file,
        fasta_dedupe=fasta_dedupe.value,
        processes=processes,
        mode=mode.value,
        scaffold_subdirs=scaffold_subdirs,
        single_output=single_output,
        verbose=verbose,
        profile=profile,
        verify_hash=verify_hash,
    )
    cmdline = "mafutils fetch"
    if len(sys.argv) > 2:
        cmdline += " " + " ".join(sys.argv[2:])
    run_fetch(args, cmdline=cmdline)
